const CONFIG = {
  services: {
    wifi: { ssid: "", pass: "" },
    telegram: { enabled: false, tg_tok: "", ids_c: 1, ids: [] },
    mqtt: {
      enabled: false,
      m_ip: "",
      m_port: "",
      m_u: "",
      m_p: "",
      m_t: "",
      m_i: 5,
    },
    web: { w_u: "", w_p: "" },
  },
  sensors: {
    bme280: {
      enabled: true,
      name: "BME280",
      titles: [
        "Температура воздуха, °C",
        "Влажность воздуха, %",
        "Давление воздуха, Pa",
      ],
      topics: ["/bme280/t", "/bme280/h", "/bme280/p"],
      cards: ["card-bme-t", "card-bme-h", "card-bme-p"],
    },

    dht22: {
      enabled: false,
      name: "DHT22",
      titles: ["Температура воздуха, °C", "Влажность воздуха, %"],
      cards: ["card-dht-t", "card-dht-h"],
      topics: ["/dht22/t", "/dht22/h"],
      gpio: 15,
    },
    tcrt5000: {
      enabled: false,
      name: "TCRT5000",
      title: "Освещение",
      cards: ["card-lux-tcrt"],
      topics: ["/tcrt5000"],
    },
    resistor5516: {
      enabled: false,
      name: "Resistor5516",
      title: "Освещение",
      cards: ["card-lux-5516"],
      topics: ["/ldr5516"],
      gpio: 39,
    },
    pir: {
      enabled: false,
      name: "SR501",
      title: "Движение",
      cards: ["card-pir"],
      topics: ["/sr501"],
      gpio: 35,
    },
    presence: {
      enabled: false,
      name: "LD2420",
      title: "Присутствие",
      cards: ["card-pres"],
      topics: ["/ld2420"],
      gpio: 35,
    },
    ds18b20: {
      enabled: true,
      name: "DS18B20",
      titles: [
        "Температура T1, °C",
        "Температура T2, °C",
        "Температура T3, °C",
        "Температура T4, °C",
      ],
      macs: ["", "", "", ""],
      cards: ["card-t1", "card-t2", "card-t3", "card-t4"],
      topics: ["/ds18b20/t1", "/ds18b20/t2", "/ds18b20/t3", "/ds18b20/t4"],
      gpio: 4,
      col: 0,
    },
    door: {
      enabled: false,
      name: "Door",
      title: "Дверь",
      cards: ["card-door"],
      gpio: 1,
    },
    flood: {
      enabled: false,
      name: "Fluid resistor",
      title: "Затопление",
      cards: ["card-flood"],
      gpio: 1,
    },
    relay: {
      enabled: false,
      name: "RELEx4",
      titles: ["Розетка 1", "Розетка 2", "Розетка 3", "Розетка 4"],
      cards: ["card-r0", "card-r1", "card-r2", "card-r3"],
      gpio: [26, 27, 14, 13],
      col: 0,
    },
  },
};
